AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Deploy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Policies:
        - AmazonEC2ContainerServiceFullAccess
        - AWSCodePipelineCustomActionAccess